### ISSUE TITLE
LineageOS 17.x+ backport?

### ISSUE THREAD

**Issue by simonsan** [LineageOS/android_packages_apps_Seedvault#1]
In the requirements it's stated that `Android 11` will be needed, will SeedVault be ported back to/included in LineageOS 17.x+ as well?

Otherwise is there a solution you can recommend? With the missing su-Addon for LOS17 it's a bit harder to make a complete backup and I'm not a big fan of installing Magisk (and keep it updated) for this purpose nor am I able to install Titanium due to non-root issues.

**Comment by bananer** [comment]
It should be included in the most recent builds for LineageOS 17.1

I run my own 17.1 builds and can confirm that Seedvault is present in the Settings. Backing up to Nextcloud seems to be working, have not tested restore yet though.

**Comment by simonsan** [comment]
> 
> 
> It should be included in the most recent builds for LineageOS 17.1
> 
> I run my own 17.1 builds and can confirm that Seedvault is present in the Settings. Backing up to Nextcloud seems to be working, have not tested restore yet though.

Ah ok, the build for my device (klte) is a bit older, so probably with the next update. Thanks for telling. Cheers.

**Comment by simonsan** [comment]
> 
> 
> It should be included in the most recent builds for LineageOS 17.1
> 
> I run my own 17.1 builds and can confirm that Seedvault is present in the Settings. Backing up to Nextcloud seems to be working, have not tested restore yet though.

How did you get Nextcloud to work? I have three different accounts but also a device that is encrypted with a password and it doesn't let me add Nextcloud as a provider. 🤔

**Comment by darhma** [comment]
@simonsan if you have enabled a password or device credential to access nextcloud you need to disable it. Upstream issue was closed and you can see it here: https://github.com/stevesoltys/seedvault/issues/82
